version: '3.9'

services:
  database:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: numanddrive_db
    container_name: database
    image: mysql:8.1
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - numanddrive_volume:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - numanddrive_networks
  
  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - database
    networks:
      - numanddrive_networks

volumes:
  numanddrive_volume:

networks:
  numanddrive_networks:
    driver: bridge
