name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup environment variables
      run: |
        echo "DB_SERVER=${{ secrets.DB_SERVER }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore ./NumAndDrive.Project/NumAndDrive/NumAndDrive.csproj

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output ./output ./NumAndDrive.Project/NumAndDrive/NumAndDrive.csproj

    - name: Deploy to Server
      if: success()
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "./output"
        target: "/var/www/numanddrive/publish"

    - name: Restart application
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo systemctl restart numanddrive

    - name: Print error logs
      if: failure()
      run: |
        echo "##[error] Build failed"
        find . -name "*.csproj"
        cat ./NumAndDrive.Project/NumAndDrive/NumAndDrive.csproj
        dotnet --info
        dotnet build --configuration Release --project ./NumAndDrive.Project/NumAndDrive/NumAndDrive.csproj -v diag
